import { Player } from "../../../_types/playerData";
// this is the clean sheet game state used in "MainGame" component.
// the positions are used by the "Pitch.tsx" component when passed as props to map over and
// render each player's icon and name in the correct position on the pitch.

// legacy implementation but still used, needs to be refactored.
const placeholderImage = "";
const gameState433: Player[] = [
  {
    role: "RB",
    playerRow: 6,
    playerCol: 8,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "RCB",
    playerRow: 6,
    playerCol: 6,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LCB",
    playerRow: 6,
    playerCol: 4,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LB",
    playerRow: 6,
    playerCol: 2,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "RCM",
    playerRow: 4,
    playerCol: 6,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "DMF",
    playerRow: 5,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LCM",
    playerRow: 4,
    playerCol: 4,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "RWF",
    playerRow: 3,
    playerCol: 8,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "CF",
    playerRow: 2,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LWF",
    playerRow: 3,
    playerCol: 2,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "GK",
    playerRow: 7,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
];

const gameState3142: Player[] = [
  {
    role: "RCB",
    playerRow: 6,
    playerCol: 7,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "MCB",
    playerRow: 6,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LCB",
    playerRow: 6,
    playerCol: 3,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "DMF",
    playerRow: 5,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "RCM",
    playerRow: 4,
    playerCol: 6,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "RMF",
    playerRow: 4,
    playerCol: 8,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LCM",
    playerRow: 4,
    playerCol: 4,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LMF",
    playerRow: 4,
    playerCol: 2,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "CF",
    playerRow: 2,
    playerCol: 4,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "SS",
    playerRow: 2,
    playerCol: 6,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "GK",
    playerRow: 7,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
];

const gameState442Diamond: Player[] = [
  {
    role: "RB",
    playerRow: 6,
    playerCol: 8,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "RCB",
    playerRow: 6,
    playerCol: 6,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LCB",
    playerRow: 6,
    playerCol: 4,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LB",
    playerRow: 6,
    playerCol: 2,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "RCM",
    playerRow: 4,
    playerCol: 6,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "DMF",
    playerRow: 5,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "LCM",
    playerRow: 4,
    playerCol: 4,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "AMF",
    playerRow: 3,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "CF",
    playerRow: 2,
    playerCol: 6,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "SS",
    playerRow: 2,
    playerCol: 4,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
  {
    role: "GK",
    playerRow: 7,
    playerCol: 5,
    playerName: "",
    profileImgUrl: placeholderImage,
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
    playerNationalFlag: "",
    playerValueDate: "",
    playerPosition: "",
    playerClubLogoUrl: "",
    playerId: 0,
    playerFifaStats: { overallRating: 0, stats: [], birthdate: "unknown" },
  },
];
const gameStates = { gameState3142, gameState433, gameState442Diamond };

export default gameStates;
