import { playerGameState } from "../types/playerData";
// this is the clean sheet game state used in "MainGame" component.
// the positions are used by the "Pitch.tsx" component when passed as props to map over and
// render each player's icon and name in the correct position on the pitch.
const gameState: playerGameState[] = [
  {
    role: "RB",
    playerRow: 5,
    playerCol: 7,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "RCB",
    playerRow: 5,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "LCB",
    playerRow: 5,
    playerCol: 3,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "LB",
    playerRow: 5,
    playerCol: 1,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "RCM",
    playerRow: 3,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "DMF",
    playerRow: 4,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "LCM",
    playerRow: 3,
    playerCol: 3,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "RWF",
    playerRow: 2,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "CF",
    playerRow: 2,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "LWF",
    playerRow: 2,
    playerCol: 2,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
  {
    role: "GK",
    playerRow: 6,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
  },
];

export default gameState;
