import { Player } from "../types/playerData";
// this is the clean sheet game state used in "MainGame" component.
// the positions are used by the "Pitch.tsx" component when passed as props to map over and
// render each player's icon and name in the correct position on the pitch.

const gameStateFTT: Player[] = [
  {
    role: "RB",
    playerRow: 6,
    playerCol: 8,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "RCB",
    playerRow: 6,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LCB",
    playerRow: 6,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LB",
    playerRow: 6,
    playerCol: 2,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "RCM",
    playerRow: 4,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "DMF",
    playerRow: 5,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LCM",
    playerRow: 4,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "RWF",
    playerRow: 3,
    playerCol: 8,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "CF",
    playerRow: 2,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LWF",
    playerRow: 3,
    playerCol: 2,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "GK",
    playerRow: 7,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
];

const gameStateTFT: Player[] = [
  {
    role: "RCB",
    playerRow: 6,
    playerCol: 7,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "MCB",
    playerRow: 6,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LCB",
    playerRow: 6,
    playerCol: 3,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "DMF",
    playerRow: 5,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "RCM",
    playerRow: 4,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "RMF",
    playerRow: 4,
    playerCol: 8,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?rmF",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LCM",
    playerRow: 4,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LMF",
    playerRow: 4,
    playerCol: 2,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "CF",
    playerRow: 2,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "SS",
    playerRow: 2,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "GK",
    playerRow: 7,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
];

const gameStateFFTDia: Player[] = [
  {
    role: "RB",
    playerRow: 6,
    playerCol: 8,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "RCB",
    playerRow: 6,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LCB",
    playerRow: 6,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LB",
    playerRow: 6,
    playerCol: 2,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "RCM",
    playerRow: 4,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "DMF",
    playerRow: 5,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "LCM",
    playerRow: 4,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "AMF",
    playerRow: 3,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "CF",
    playerRow: 2,
    playerCol: 6,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "SS",
    playerRow: 2,
    playerCol: 4,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
  {
    role: "GK",
    playerRow: 7,
    playerCol: 5,
    playerName: "",
    profileImgUrl: "https://placehold.co/80x70/png?text=?",
    playerValue: 0,
    clubName: "",
    playerAge: "",
    playerFoot: "",
    playerLeague: "",
    playerCountry: "",
    playerHeight: "",
    fullPlayerName: "",
    shortPlayerName: "",
  },
];

export default { gameStateFTT, gameStateTFT, gameStateFFTDia };
